version: '3.8'

services:
  nginx:
    build:
      context: ./infra/docker/nginx
      dockerfile: Dockerfile
    container_name: zentora-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - zentora-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ../../infra/docker/frontend/Dockerfile
    container_name: zentora-frontend
    expose:
      - "3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - zentora-network

  backend:
    build:
      context: ./apps/backend
      dockerfile: ../../infra/docker/backend/Dockerfile
    container_name: zentora-backend
    expose:
      - "8000"
    volumes:
      - ./apps/backend:/app
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    restart: unless-stopped
    networks:
      - zentora-network

networks:
  zentora-network:
    driver: bridge
