import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { NotificationProvider } from "@/context/NotificationContext";
import { NotificationContainer } from "@/components/Notification/NotificationContainer";
import { AuthProvider } from "@/context/AuthContext";
import { ChatProvider } from "@/context/ChatContext";
import { AssetsProvider } from "@/context/AssetsContext";

export const metadata: Metadata = {
  title: "Bienvenido a Zentora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="antialiased bg-light-bg text-text-primary dark:bg-dark-bg dark:text-dark-text-primary">
        <NotificationProvider>
          <AuthProvider>
            <ChatProvider>
              <AssetsProvider>
                <ThemeProvider>
                  <NotificationContainer />
                  {children}
                </ThemeProvider>
              </AssetsProvider>
            </ChatProvider>
          </AuthProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
