import type { Metadata } from "next";
import "./globals.css";
import { ThemeButton } from "@/components/ThemeButton";
import { ThemeProvider } from "@/context/ThemeContext";
import { NotificationProvider } from "@/context/NotificationContext";
import { NotificationContainer } from "@/components/Notification/NotificationContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="antialiased bg-background text-text-primary dark:bg-background-dark dark:text-text-primary-dark">
        <NotificationProvider>
          <ThemeProvider>
            <ThemeButton />
            <NotificationContainer />
            {children}
          </ThemeProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
